### ISSUE TITLE
add support to clear and unset a flag and opt out of default flags

### ISSUE THREAD

**Issue by Madpeterz** [Madpeterz/YAPFbootstrap#1]
currently the SITE_URL flag is set (and invaild) with the module, area and catche status flags there should be a way to opt out of having them.

also it would be nice to have a way to clear a flag and unset it

```
$this->clearFlag("flagName");
```

**Comment by shadoskill** [comment]
Fit it, fit it,  fit it,  fit it,  fit it,  fit it,  fit it,  fit it,  fit it,  fit it.

**Comment by Madpeterz** [comment]
done
